plugins {
    id 'com.android.library'
    id 'dagger.hilt.android.plugin'
}

apply from: moduleGradle

android {
    namespace 'com.dp.notes'
    resourcePrefix "notes_"
}

dependencies {
    //hilt
    implementation deps.Inject.hilt
    kapt deps.Inject.compiler
    //Arouter
    kapt deps.Arouter.compiler
    implementation deps.Inject.koin
    implementation deps.Depend.flexbox
    //----------------
    implementation project(':module-common')
    implementation project(':module-webview')
    includeApi(':module-ztest-include')
    //implementation 'com.tencent.mars:mars-xlog:1.2.5'
}