plugins {
    id 'com.android.library'
    id 'dagger.hilt.android.plugin'
}

apply from: moduleGradle

android {
    namespace 'com.dp.notes'
    resourcePrefix "notes_"
}

dependencies {
    //hilt
    implementation deps.Inject.hilt
    kapt deps.Inject.compiler
    //Arouter
    kapt deps.Arouter.compiler
    //-------
    implementation project(':module-common')
    compileOnly project(':module-webview')
    compileApi(':module-ztest-include')
    //-------
    implementation deps.Inject.koin
    implementation deps.Depend.flexbox
    //implementation 'com.tencent.mars:mars-xlog:1.2.5'
}